version: "3.8"

services:
  db:
    image: postgres:15
    container_name: langgraph_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./fastapi-backend
    container_name: langgraph_backend
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build: ./angular-frontend
    container_name: langgraph_frontend
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  db_data:
